name: InfAir
version: 1.2
main: com.laxwashere.InfAir.InfAir
author: LaxWasHere
website: www.LaxWasHere.com
commands:
    air:
        description: Gives you infinite air while under water.
        permission: infair.air
        aliases: infair
        
permissions:
  infair.air:
    description: Allows the use of the air command.
    default: op